version: "3"

services:
  cert-builder:
    image: keycloak-example/cert_builder
    build:
      context: certs/docker 
      dockerfile: Dockerfile 
    command: nginx
    volumes:
      - ./certs:/certs
      - ./nginx_data:/logging
    environment:
      - OUTPUT=/certs
      - CONF=/certs/_conf
  keycloak:
    image: keycloak/keycloak:latest
    #image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: secretpassword
      KC_HTTP_RELATIVE_PATH: /auth
      # worked in previous versions
      # KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      LOGIN_HOST_PORT: nginx.keycloak-example.loc
      KC_HOSTNAME: nginx.keycloak-example.loc
      DB_VENDOR: h2
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import.json:/opt/keycloak/data/import/import.json
  nginx.keycloak-example.loc:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./certs:/certs
      - ./nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - cert-builder
      - keycloak
